### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by niclowe** [rietta/git_time_extractor#14]
Can you please give an example of how to use the -p PROJECT switch?
I've havent been able to do my whole project because Ive been using the -i switch and it seems like its missing git in subfolders.

**Comment by rietta** [comment]
The -p switch is just a arbitrary label/string that is then added to the output. This way if you have multiple projects and cat the results together, you have a column to pivot on in a spreadsheet.

**Comment by rietta** [comment]
-i is the full path to a single repository. Time time extractor does not recursively search sub directories for repos.  There may be a way to do that with the `find` command and `git_time_extractor`.

**Comment by rietta** [comment]
Something like this as a base
http://www.sixarm.com/about/git-how-to-find-git-repository-directories.html

**Comment by rietta** [comment]
For example, this would work recursively for all git repositories in subfolders:

`find /project/parent/path -type d -name .git | xargs -n 1 dirname | xargs -n 1 git_time_extractor -i`

The commands in use are:
- find: http://www.unix.com/man-page/freebsd/1/find/
- xargs: http://www.unix.com/man-page/freebsd/1/xargs/
- dirname: http://www.unix.com/man-page/freebsd/1/dirname/

Basically, find is locating the .git folders, dirname is extracting the project path for each repo, and then git_time_extractor is processing each of those projects one after another. You can pipe the output to a CSV file as usual, for example:

`find /project/parent/path -type d -name .git | xargs -n 1 dirname | xargs -n 1 git_time_extractor -i > ~/Documents/report.csv`
