### ISSUE TITLE
Selecting a branch

### ISSUE THREAD

**Issue by danimalweb** [rietta/git_time_extractor#16]
This is great.

By default this has run against the master branch in my repo, is there an argument I can pass to tell it to use another branch?

Thanks.

**Comment by rietta** [comment]
Have you tried checking out the branch you want to scan and then run the git_time_extractor command?

**Comment by rietta** [comment]
`git checkout feature_branch && git_time_extractor`

**Comment by benzkji** [comment]
runs on currently checked out branch for me, too.

**Comment by danimalweb** [comment]
All good.
