### ISSUE TITLE
undefined method `to_date'

### ISSUE THREAD

**Issue by mturley** [rietta/git_time_extractor#2]
I've been trying to get this running, but for some reason every time I try to run git_time_extractor I get the following error.  The same thing happens in OSX and Ubuntu.

Anyone know how I can fix this?

/Library/Ruby/Gems/1.8/gems/git_time_extractor-0.2.1/bin/../lib/git_time_extractor.rb:44:in `process_git_log_into_time': undefined method`to_date' for Sat Jan 18 00:46:58 -0500 2014:Time (NoMethodError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `each_with_index'
    from /Library/Ruby/Gems/1.8/gems/git_time_extractor-0.2.1/bin/../lib/git_time_extractor.rb:43:in`each'
    from /Library/Ruby/Gems/1.8/gems/git_time_extractor-0.2.1/bin/../lib/git_time_extractor.rb:43:in `each_with_index'
    from /Library/Ruby/Gems/1.8/gems/git_time_extractor-0.2.1/bin/../lib/git_time_extractor.rb:43:in`process_git_log_into_time'
    from /Library/Ruby/Gems/1.8/gems/git_time_extractor-0.2.1/bin/git_time_extractor:43
    from /usr/bin/git_time_extractor:19:in `load'
    from /usr/bin/git_time_extractor:19

**Comment by niclowe** [comment]
I am having exactly the same error as this.

**Comment by niclowe** [comment]
I used 1.9.3 and 2.2x64
