### ISSUE TITLE
proposal: compact mode

### ISSUE THREAD

**Issue by benzkji** [rietta/git_time_extractor#7]
add a new flag: 

    --compact

that first does the same calculations, but then shows an overview with
- total working hours
- total commits
- list all collaborators
- show working time time period

a bit like git-hours, but not that reduced.

**Comment by rietta** [comment]
Good idea. Some of that can be accomplished now by opening the CSV in a spreadsheet and then running the summary. But, I like your idea.

**Comment by rietta** [comment]
Do you have the ability to add it and submit a pull request?

**Comment by benzkji** [comment]
I could try. Not into ruby at all for now...

**Comment by benzkji** [comment]
irb
require 'GitTimeExtractor'
e = new GitTimeExtractor()
e.whatever...

=> easier way to test it? ;-)

**Comment by rietta** [comment]
Adding an automated test suite is in the plans. I actually opened an issue for it.  

Don't worry about adding this if you do not want. It's along the lines of an idea that I had, but I should be able to add it in sometime soon.

**Comment by rietta** [comment]
If you need to run this report for today, take a look at https://github.com/rietta/git_time_extractor/blob/master/examples/example_1_analysis.xlsx

That's how I've done some similar analysis on projects using the raw timing data from GTE.

**Comment by rietta** [comment]
Pivot Tables are your friend in this case.

**Comment by benzkji** [comment]
thx! not that urgent, no. just curios, do you normally use irb for testing it?

**Comment by rietta** [comment]
Yes, IRB and running the script from the command line against its repo and others. This started out as a toy project and grew from there.

**Comment by rietta** [comment]
Ben,

Your changes have been merged in and published with the official gem. Thank you!

Frank
